### ISSUE TITLE
Sometimes ZMQ freezes on sendExpression("quit()")

### ISSUE THREAD

**Issue by CSchoel** [OpenModelica/OMJulia.jl#32]
Sometimes (maybe 1 in 10 or 1 in 20 cases), ZMQ freezes after `sendExpression(omc, "quit()")`.

The OMC instance shuts down properly, but the call never returns. I suppose that this could be a threading issue on the side of OMC so that `quit()` sometimes shuts down the process before the answer to the ZMQ message is sent.

The clean solution would probably be to look into the ZMQ handling in the OMC, but a quick fix could also be to simply skip the call to `ZMQ.recv` for the `quit()` message like this:

```julia
...
if expr == "quit()"
    return ""
end
message=ZMQ.recv(omc.socket)
...
```

If it seems that this clutters up the implementation of `sendExpression` too much, it would also be possible to implement `quit(omc)` as a separate function.

**Comment by adeas31** [comment]
@arun3688 Isn't it already fixed. See #12 and #29.

**Comment by JKRT** [comment]
@arun3688 @adeas31 I think the issue might be due to the official version of this package has not been updated maybe.. 

@CSchoel Could you try the code from this repo and verify this to us?

**Comment by arun3688** [comment]
@adeas31 , Yes this is fixed as John pointed it out, @CSchoel  may be using the oder version

**Comment by adeas31** [comment]
Well looking at the code I think the problem is still there. You only check for the process before send. If we send "quit()" it will kill the process so I think you have to check for it before receive as well.

**Comment by arun3688** [comment]
@adeas31 i will add it

**Comment by JKRT** [comment]
@arun3688 still, did you release a new version of OMJulia after the fix?

**Comment by arun3688** [comment]
@JKRT you mean which fix, this issue

**Comment by JKRT** [comment]
@JKRT Did we cover this yesterday?

**Comment by CSchoel** [comment]
> @arun3688 @adeas31 I think the issue might be due to the official version of this package has not been updated maybe..
> 
> @CSchoel Could you try the code from this repo and verify this to us?

I already used the latest repository version (commit hash `77e7fe0684c8dc6b60cc668fcf1f2ec89c43581e`) for my tests, because I needed the fix for #22 to be able to send the `quit()` command.

I think @adeas31 is right: The fix for #29 does not work in this case, because the omc process is killed after the process status was checked.
